### PR TITLE
cpld: improve the auto-selection of the device

### PR DESCRIPTION
**Pull request by rshym**
We can have a few different FTDI devices with VID:PID specified by cpld_profile, e.g.: serial port and relays.
This patch adds additional logic to auto-select a serial port in such cases.
See the internal comment for a step-by-step explanation.

### CODE REVIEW

**Comment by lorc** [comment]
Problem with that PR is that is is ULCB-only. For example, S4/Spider uses completely different FTDI chip. So, we can't rely on hardcoded FTDI names. I believe, best way is to infer serial number from `/dev/ttyUSBx` path. AFAIK, `pyserial` already has this functionality. We just need to rework device discovery procedures. 

Quick solution is to just return an error if we found more than one compatible FTDI device to force user to provide serial number in such cases.

**Comment by rshym** [comment]
> AFAIK, pyserial already has this functionality

Maybe I will try `class serial.tools.list_ports.ListPortInfo`. I see some `serial_number USB serial number as a string.`

**Comment by rshym** [comment]
PR is reworked according to the off-site discussion.

**Comment by rshym** [comment]
Tested three use cases on the setup with two devices with the same VID:PID:
1. CPLD auto, `-s` is specified
`sudo python3 ./rcar_flash.py flash -c -f -p ../firmware_dunfell_kf/ -s /dev/ttyUSB0 -b h3ulcb_4x2 bootparam`
2. CPLD auto, `-s` is NOT specified
`sudo python3 ./rcar_flash.py flash -c -f -p ../firmware_dunfell_kf/ -b h3ulcb_4x2 bootparam`
3. CPLD specified `-s` is not specified
`sudo python3 ./rcar_flash.py flash -c A602DN1Y -f -p ../firmware_dunfell_kf/ -b h3ulcb_4x2 bootparam`

In all cases, the script worked as expected.

**Comment by lorc** [comment]
Looks good, thank you

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Pull request merged**
