### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by rshym**
- Add usage examples to the README.md
- Add table of contents to README.md

### CODE REVIEW

**Comment by rshym** [comment]
This PR address https://github.com/xen-troops/rcar_flash/issues/23

**Comment by rshym** [comment]
Each item in the table of contents was tested to have the correct link.

**Review by lorc — APPROVED** [review]
Great work!

`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
`R-b` is added.
ToC is tested.
Ready to be merged.

**Pull request merged**
