### PR TITLE
Use path provided by --path

### PR DESCRIPTION
**Pull request by rshym**
Path specified by the user is now used to read loaders.

### CODE REVIEW

**Comment by lorc** [comment]
What about `.mot` file? Are we expecting that it will be located in the same directory with loaders? 

I am not asking to add support for this, I am curious about your opinion.

**Comment by rshym** [comment]
I would propose to:
- provide .mot-files in this repo, if we have no legal restrictions
- collect .mot-files into 'mot' directory (now we have 7 different files in yaml)

Maybe we may implement some logic like searching in the current directory, then in 'mot' directory. Not sure that this is needed.

But, taking into account that we may provide a few binaries (x86 and ARM) for CPLD-control, we may put them together into the same directory and name it 'ext_tools', for example.

**Comment by lorc** [comment]
Well, flash writer for gen3 is under BSD3 licence, so we can provide binaries there.

On other hand, flash writer for Gen4 is nowhere to be found... But that's the completely other story. Anyways, I am okay with idea to store .mot files together with `rcar_flash`. So,

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
`Ack` is added. Tested. Ready to be merged.

**Pull request merged**
