### PR TITLE
Add support for V4H Whitehawk board

### PR DESCRIPTION
**Pull request by rshym**
Add corresponding description ito the yaml and README.md.

### CODE REVIEW

**Comment by rshym** [comment]
README is updated.
Tested on the Whitehawk board.

**Comment by rshym** [comment]
@lorc could you please take a look? I have reworked the README.

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
`Ack` is added.
Tested.
Ready to be merged.

**Pull request merged**
